"""Reference rows the app ships with (were inserted by the SQL migrations)."""

PLANS = [
    {'id': 'basic', 'tier': 'basic', 'months': None, 'price_cents': 0, 'monthly_table_limit': 3, 'monthly_join_limit': None, 'sort': 0, 'active': True},
    {'id': 'premium_1m', 'tier': 'premium', 'months': 1, 'price_cents': 999, 'monthly_table_limit': None, 'monthly_join_limit': None, 'sort': 1, 'active': True},
    {'id': 'premium_3m', 'tier': 'premium', 'months': 3, 'price_cents': 2499, 'monthly_table_limit': None, 'monthly_join_limit': None, 'sort': 2, 'active': True},
    {'id': 'premium_12m', 'tier': 'premium', 'months': 12, 'price_cents': 5999, 'monthly_table_limit': None, 'monthly_join_limit': None, 'sort': 3, 'active': True},
]

LESSON_SUBJECTS = [
    {'id': 'drawing_painting', 'category': 'art', 'sort': 1},
    {'id': 'photography', 'category': 'art', 'sort': 2},
    {'id': 'video_editing', 'category': 'art', 'sort': 3},
    {'id': 'calligraphy', 'category': 'art', 'sort': 4},
    {'id': 'public_speaking', 'category': 'career', 'sort': 1},
    {'id': 'cv_interview', 'category': 'career', 'sort': 2},
    {'id': 'entrepreneurship', 'category': 'career', 'sort': 3},
    {'id': 'personal_finance', 'category': 'career', 'sort': 4},
    {'id': 'sales_marketing', 'category': 'career', 'sort': 5},
    {'id': 'project_management', 'category': 'career', 'sort': 6},
    {'id': 'chess', 'category': 'hobbies', 'sort': 1},
    {'id': 'cooking', 'category': 'hobbies', 'sort': 2},
    {'id': 'driving_theory', 'category': 'hobbies', 'sort': 3},
    {'id': 'sewing', 'category': 'hobbies', 'sort': 4},
    {'id': 'gardening', 'category': 'hobbies', 'sort': 5},
    {'id': 'english', 'category': 'languages', 'sort': 1},
    {'id': 'german', 'category': 'languages', 'sort': 2},
    {'id': 'french', 'category': 'languages', 'sort': 3},
    {'id': 'italian', 'category': 'languages', 'sort': 4},
    {'id': 'spanish', 'category': 'languages', 'sort': 5},
    {'id': 'turkish', 'category': 'languages', 'sort': 6},
    {'id': 'albanian', 'category': 'languages', 'sort': 7},
    {'id': 'serbian_croatian', 'category': 'languages', 'sort': 8},
    {'id': 'macedonian', 'category': 'languages', 'sort': 9},
    {'id': 'russian', 'category': 'languages', 'sort': 10},
    {'id': 'arabic', 'category': 'languages', 'sort': 11},
    {'id': 'chinese', 'category': 'languages', 'sort': 12},
    {'id': 'japanese', 'category': 'languages', 'sort': 13},
    {'id': 'swedish', 'category': 'languages', 'sort': 14},
    {'id': 'sign_language', 'category': 'languages', 'sort': 15},
    {'id': 'piano', 'category': 'music', 'sort': 1},
    {'id': 'guitar', 'category': 'music', 'sort': 2},
    {'id': 'violin', 'category': 'music', 'sort': 3},
    {'id': 'singing', 'category': 'music', 'sort': 4},
    {'id': 'drums', 'category': 'music', 'sort': 5},
    {'id': 'music_theory', 'category': 'music', 'sort': 6},
    {'id': 'accordion', 'category': 'music', 'sort': 7},
    {'id': 'math', 'category': 'school', 'sort': 1},
    {'id': 'physics', 'category': 'school', 'sort': 2},
    {'id': 'chemistry', 'category': 'school', 'sort': 3},
    {'id': 'biology', 'category': 'school', 'sort': 4},
    {'id': 'albanian_literature', 'category': 'school', 'sort': 5},
    {'id': 'history', 'category': 'school', 'sort': 6},
    {'id': 'geography', 'category': 'school', 'sort': 7},
    {'id': 'informatics', 'category': 'school', 'sort': 8},
    {'id': 'homework_help', 'category': 'school', 'sort': 9},
    {'id': 'early_reading', 'category': 'school', 'sort': 10},
    {'id': 'programming', 'category': 'tech', 'sort': 1},
    {'id': 'web_development', 'category': 'tech', 'sort': 2},
    {'id': 'mobile_development', 'category': 'tech', 'sort': 3},
    {'id': 'data_science', 'category': 'tech', 'sort': 4},
    {'id': 'ai_ml', 'category': 'tech', 'sort': 5},
    {'id': 'cybersecurity', 'category': 'tech', 'sort': 6},
    {'id': 'excel_office', 'category': 'tech', 'sort': 7},
    {'id': 'ui_ux_design', 'category': 'tech', 'sort': 8},
    {'id': 'graphic_design', 'category': 'tech', 'sort': 9},
    {'id': 'digital_marketing', 'category': 'tech', 'sort': 10},
    {'id': 'ielts', 'category': 'tests', 'sort': 1},
    {'id': 'toefl', 'category': 'tests', 'sort': 2},
    {'id': 'cambridge', 'category': 'tests', 'sort': 3},
    {'id': 'goethe', 'category': 'tests', 'sort': 4},
    {'id': 'testdaf', 'category': 'tests', 'sort': 5},
    {'id': 'delf', 'category': 'tests', 'sort': 6},
    {'id': 'sat', 'category': 'tests', 'sort': 7},
    {'id': 'gre_gmat', 'category': 'tests', 'sort': 8},
    {'id': 'state_matura', 'category': 'university', 'sort': 1},
    {'id': 'university_entrance', 'category': 'university', 'sort': 2},
    {'id': 'calculus', 'category': 'university', 'sort': 3},
    {'id': 'statistics', 'category': 'university', 'sort': 4},
    {'id': 'economics', 'category': 'university', 'sort': 5},
    {'id': 'accounting', 'category': 'university', 'sort': 6},
    {'id': 'law', 'category': 'university', 'sort': 7},
    {'id': 'medicine_prep', 'category': 'university', 'sort': 8},
    {'id': 'engineering', 'category': 'university', 'sort': 9},
    {'id': 'thesis_help', 'category': 'university', 'sort': 10},
    {'id': 'personal_training', 'category': 'wellbeing', 'sort': 1},
    {'id': 'yoga', 'category': 'wellbeing', 'sort': 2},
    {'id': 'swimming', 'category': 'wellbeing', 'sort': 3},
    {'id': 'martial_arts', 'category': 'wellbeing', 'sort': 4},
    {'id': 'dance', 'category': 'wellbeing', 'sort': 5},
    {'id': 'nutrition', 'category': 'wellbeing', 'sort': 6},
]

NOTIFICATION_TEXT_RULES = [
    {'kind': 'requestNew', 'lang': 'sq', 'pattern': '^(.*) kërkon t\'i bashkohet "(.*)"\\.', 'param_names': ['name', 'title'], 'priority': 10},
    {'kind': 'requestApprovedGuest', 'lang': 'sq', 'pattern': '^U aprovove për "(.*)"\\.', 'param_names': ['title'], 'priority': 10},
    {'kind': 'waitlistSpot', 'lang': 'sq', 'pattern': '^U lirua një vend te "(.*)"', 'param_names': ['title'], 'priority': 10},
    {'kind': 'mutualMatch', 'lang': 'sq', 'pattern': '^Përputhje e ndërsjellë!', 'param_names': [], 'priority': 10},
    {'kind': 'accountSuspended', 'lang': 'sq', 'pattern': '^Llogaria juaj u pezullua\\. Arsyeja: (.*)\\. Pezullim (\\d+)/3\\.?$', 'param_names': ['reason', 'count'], 'priority': 10},
    {'kind': 'tableCancelledByAdmin', 'lang': 'sq', 'pattern': '^Tavolina "(.*)" u anulua nga ekipi i ejaBashkohu\\. Arsyeja: (.*)$', 'param_names': ['title', 'reason'], 'priority': 10},
    {'kind': 'badgeEarned', 'lang': 'sq', 'pattern': '^Fitove distinktivin "(.*?)"! Shikoje te Tavolinat e mia\\.$', 'param_names': ['label'], 'priority': 50},
    {'kind': 'tasteProfileSaved', 'lang': 'sq', 'pattern': '^Profili i shijeve u ruajt\\. Tavolinat renditen sipas teje\\.$', 'param_names': [], 'priority': 50},
    {'kind': 'tasteProfileLocalFailed', 'lang': 'sq', 'pattern': '^Profili i shijeve u krijua lokalisht\\. Ruajtja në server dështoi\\. Provo sërish më vonë\\.$', 'param_names': [], 'priority': 50},
    {'kind': 'seatConfirmedRide', 'lang': 'sq', 'pattern': '^Ulësja u konfirmua! Shihemi te nisja: (.*?), (.*?)\\.$', 'param_names': ['area', 'time'], 'priority': 50},
    {'kind': 'seatConfirmedTicket', 'lang': 'sq', 'pattern': '^Vendi u konfirmua! Bileta jote: (.*?)$', 'param_names': ['code'], 'priority': 50},
    {'kind': 'reportSubmitted', 'lang': 'sq', 'pattern': '^Raporti u dërgua\\. Ekipi ynë e shqyrton brenda 24 orësh\\.$', 'param_names': [], 'priority': 50},
    {'kind': 'requestApproved', 'lang': 'sq', 'pattern': '^Kërkesa u aprovua\\. Personi duhet të konfirmojë vendin\\.$', 'param_names': [], 'priority': 50},
    {'kind': 'wednesdayMatch', 'lang': 'sq', 'pattern': '^U përputhe me 5 persona për Darkën e së Mërkurës! Konfirmo vendin\\. Restoranti zbulohet 24h para\\.$', 'param_names': [], 'priority': 50},
    {'kind': 'hostSeatConfirmedNotif', 'lang': 'sq', 'pattern': '^(.*?) konfirmoi vendin te "(.*?)"\\.$', 'param_names': ['guest', 'table'], 'priority': 50},
    {'kind': 'tableClosedByHostNotif', 'lang': 'sq', 'pattern': '^Tavolina "(.*?)" u mbyll nga nikoqiri\\.$', 'param_names': ['table'], 'priority': 50},
    {'kind': 'badgeEarned', 'lang': 'en', 'pattern': '^You earned the "(.*?)" badge! See it under My tables\\.$', 'param_names': ['label'], 'priority': 50},
    {'kind': 'tasteProfileSaved', 'lang': 'en', 'pattern': '^Taste profile saved\\. Tables are ranked for you\\.$', 'param_names': [], 'priority': 50},
    {'kind': 'tasteProfileLocalFailed', 'lang': 'en', 'pattern': '^Taste profile saved locally\\. Server sync failed\\. Try again later\\.$', 'param_names': [], 'priority': 50},
    {'kind': 'seatConfirmedRide', 'lang': 'en', 'pattern': '^Seat confirmed! See you at departure: (.*?), (.*?)\\.$', 'param_names': ['area', 'time'], 'priority': 50},
    {'kind': 'seatConfirmedTicket', 'lang': 'en', 'pattern': '^Seat confirmed! Your ticket: (.*?)$', 'param_names': ['code'], 'priority': 50},
    {'kind': 'reportSubmitted', 'lang': 'en', 'pattern': '^Report submitted\\. Our team reviews it within 24 hours\\.$', 'param_names': [], 'priority': 50},
    {'kind': 'requestApproved', 'lang': 'en', 'pattern': '^Request approved\\. The person must confirm their seat\\.$', 'param_names': [], 'priority': 50},
    {'kind': 'wednesdayMatch', 'lang': 'en', 'pattern': '^Matched with 5 people for Wednesday Dinner! Confirm your seat\\. Restaurant revealed 24h before\\.$', 'param_names': [], 'priority': 50},
    {'kind': 'hostSeatConfirmedNotif', 'lang': 'en', 'pattern': '^(.*?) confirmed their seat at "(.*?)"\\.$', 'param_names': ['guest', 'table'], 'priority': 50},
    {'kind': 'tableClosedByHostNotif', 'lang': 'en', 'pattern': '^Table "(.*?)" was closed by the host\\.$', 'param_names': ['table'], 'priority': 50},
    {'kind': 'badgeEarned', 'lang': 'de', 'pattern': '^Abzeichen "(.*?)" erhalten! Sieh es unter Meine Tische\\.$', 'param_names': ['label'], 'priority': 50},
    {'kind': 'tasteProfileSaved', 'lang': 'de', 'pattern': '^Geschmacksprofil gespeichert\\. Tische werden für dich sortiert\\.$', 'param_names': [], 'priority': 50},
    {'kind': 'tasteProfileLocalFailed', 'lang': 'de', 'pattern': '^Geschmacksprofil lokal gespeichert\\. Server-Sync fehlgeschlagen\\. Später erneut versuchen\\.$', 'param_names': [], 'priority': 50},
    {'kind': 'seatConfirmedRide', 'lang': 'de', 'pattern': '^Platz bestätigt! Treffpunkt: (.*?), (.*?)\\.$', 'param_names': ['area', 'time'], 'priority': 50},
    {'kind': 'seatConfirmedTicket', 'lang': 'de', 'pattern': '^Platz bestätigt! Dein Ticket: (.*?)$', 'param_names': ['code'], 'priority': 50},
    {'kind': 'reportSubmitted', 'lang': 'de', 'pattern': '^Meldung gesendet\\. Unser Team prüft innerhalb von 24 Stunden\\.$', 'param_names': [], 'priority': 50},
    {'kind': 'requestApproved', 'lang': 'de', 'pattern': '^Anfrage genehmigt\\. Die Person muss den Platz bestätigen\\.$', 'param_names': [], 'priority': 50},
    {'kind': 'wednesdayMatch', 'lang': 'de', 'pattern': '^Mit 5 Personen für Mittwochs-Dinner gematcht! Platz bestätigen\\. Restaurant 24h vorher enthüllt\\.$', 'param_names': [], 'priority': 50},
    {'kind': 'hostSeatConfirmedNotif', 'lang': 'de', 'pattern': '^(.*?) hat den Platz bei „(.*?)“ bestätigt\\.$', 'param_names': ['guest', 'table'], 'priority': 50},
    {'kind': 'tableClosedByHostNotif', 'lang': 'de', 'pattern': '^Tisch „(.*?)“ wurde vom Gastgeber geschlossen\\.$', 'param_names': ['table'], 'priority': 50},
    {'kind': 'badgeEarned', 'lang': 'mk', 'pattern': '^Ја добив значката "(.*?)"! Види ја кај Мои маси\\.$', 'param_names': ['label'], 'priority': 50},
    {'kind': 'tasteProfileSaved', 'lang': 'mk', 'pattern': '^Профилот на вкус е зачуван\\. Масите се сортирани за тебе\\.$', 'param_names': [], 'priority': 50},
    {'kind': 'tasteProfileLocalFailed', 'lang': 'mk', 'pattern': '^Профилот е локално зачуван\\. Синхронизацијата не успеа\\. Обиди се подоцна\\.$', 'param_names': [], 'priority': 50},
    {'kind': 'seatConfirmedRide', 'lang': 'mk', 'pattern': '^Местото е потврдено! Се гледаме на тргување: (.*?), (.*?)\\.$', 'param_names': ['area', 'time'], 'priority': 50},
    {'kind': 'seatConfirmedTicket', 'lang': 'mk', 'pattern': '^Местото е потврдено! Твојот билет: (.*?)$', 'param_names': ['code'], 'priority': 50},
    {'kind': 'reportSubmitted', 'lang': 'mk', 'pattern': '^Пријавата е испратена\\. Нашиот тим ја прегледува во 24 часа\\.$', 'param_names': [], 'priority': 50},
    {'kind': 'requestApproved', 'lang': 'mk', 'pattern': '^Барањето е одобрено\\. Лицето мора да го потврди местото\\.$', 'param_names': [], 'priority': 50},
    {'kind': 'wednesdayMatch', 'lang': 'mk', 'pattern': '^Се совпадна со 5 луѓе за Среда вечера! Потврди место\\. Ресторанот се открива 24ч пред\\.$', 'param_names': [], 'priority': 50},
    {'kind': 'hostSeatConfirmedNotif', 'lang': 'mk', 'pattern': '^(.*?) го потврди местото на „(.*?)“\\.$', 'param_names': ['guest', 'table'], 'priority': 50},
    {'kind': 'tableClosedByHostNotif', 'lang': 'mk', 'pattern': '^Мasata „(.*?)“ ја затвори домаќинот\\.$', 'param_names': ['table'], 'priority': 50},
    {'kind': 'tableClosedByHostNotif', 'lang': 'mk', 'pattern': '^Масата „(.*?)“ ја затвори домаќинот\\.$', 'param_names': ['table'], 'priority': 50},
    {'kind': 'badgeEarned', 'lang': 'mk', 'pattern': '^Ја доби значката "(.*?)"! Види ја кај Мои маси\\.$', 'param_names': ['label'], 'priority': 50},
]

NOTIFICATION_BADGE_LABELS = [
    {'label': 'Complete profile', 'badge_key': 'profileComplete'},
    {'label': 'Erste Bewertung', 'badge_key': 'firstRate'},
    {'label': 'Erster Tisch', 'badge_key': 'firstJoin'},
    {'label': 'First rating', 'badge_key': 'firstRate'},
    {'label': 'First table', 'badge_key': 'firstJoin'},
    {'label': 'Neuer Gastgeber', 'badge_key': 'firstHost'},
    {'label': 'New host', 'badge_key': 'firstHost'},
    {'label': 'Nikoqiri i ri', 'badge_key': 'firstHost'},
    {'label': 'Profil i plotë', 'badge_key': 'profileComplete'},
    {'label': 'Profil vollständig', 'badge_key': 'profileComplete'},
    {'label': 'Tavolina e parë', 'badge_key': 'firstJoin'},
    {'label': 'Vlerësuesi', 'badge_key': 'firstRate'},
    {'label': 'Комpletен профил', 'badge_key': 'profileComplete'},
    {'label': 'Комплетен профил', 'badge_key': 'profileComplete'},
    {'label': 'Нов домаќин', 'badge_key': 'firstHost'},
    {'label': 'Прва маса', 'badge_key': 'firstJoin'},
    {'label': 'Прва оценка', 'badge_key': 'firstRate'},
]

# Wednesday-dinner restaurants (migration 20260811220000, links from 20260822230000)
WEDNESDAY_RESTAURANTS = [
    {'name': 'Renoma', 'city': 'Ferizaj', 'address': 'Rr. Ismail Qemali', 'maps_link': 'https://www.google.com/maps/search/?api=1&query=Renoma%2C+Rr.+Ismail+Qemali%2C+Ferizaj', 'active': True},
    {'name': 'Old Bazaar', 'city': 'Gjakovë', 'address': 'Çarshia e Vjetër', 'maps_link': 'https://www.google.com/maps/search/?api=1&query=Old+Bazaar%2C+Çarshia+e+Vjetër%2C+Gjakovë', 'active': True},
    {'name': 'Villa e Bardhe', 'city': 'Gjakovë', 'address': 'Çarshia e Madhe', 'maps_link': 'https://www.google.com/maps/search/?api=1&query=Villa+e+Bardhe%2C+Çarshia+e+Madhe%2C+Gjakovë', 'active': True},
    {'name': 'Domus', 'city': 'Gjilan', 'address': 'Rr. Bulevardi i Pavarësisë', 'maps_link': 'https://www.google.com/maps/search/?api=1&query=Domus%2C+Rr.+Bulevardi+i+Pavarësisë%2C+Gjilan', 'active': True},
    {'name': 'Fusion', 'city': 'Mitrovicë', 'address': 'Rr. Afrim Zhitia', 'maps_link': 'https://www.google.com/maps/search/?api=1&query=Fusion%2C+Rr.+Afrim+Zhitia%2C+Mitrovicë', 'active': True},
    {'name': 'Elita', 'city': 'Pejë', 'address': 'Rr. Sylejman Vokshi', 'maps_link': 'https://www.google.com/maps/search/?api=1&query=Elita%2C+Rr.+Sylejman+Vokshi%2C+Pejë', 'active': True},
    {'name': 'Trofta', 'city': 'Pejë', 'address': 'Rr. Skenderbeu', 'maps_link': 'https://www.google.com/maps/search/?api=1&query=Trofta%2C+Rr.+Skenderbeu%2C+Pejë', 'active': True},
    {'name': 'Baklori', 'city': 'Prishtinë', 'address': 'Bulevardi Bill Klinton', 'maps_link': 'https://www.google.com/maps/search/?api=1&query=Baklori%2C+Bulevardi+Bill+Klinton%2C+Prishtinë', 'active': True},
    {'name': "Dit' e Nat'", 'city': 'Prishtinë', 'address': 'Rr. Fehmi Agani', 'maps_link': 'https://www.google.com/maps/search/?api=1&query=Dit%27+e+Nat%27%2C+Rr.+Fehmi+Agani%2C+Prishtinë', 'active': True},
    {'name': 'Home 87', 'city': 'Prishtinë', 'address': 'Rr. Fazli Grajçevci', 'maps_link': 'https://www.google.com/maps/search/?api=1&query=Home+87%2C+Rr.+Fazli+Grajçevci%2C+Prishtinë', 'active': True},
    {'name': 'Home Made', 'city': 'Prishtinë', 'address': 'Rr. Sylejman Vokshi', 'maps_link': 'https://www.google.com/maps/search/?api=1&query=Home+Made%2C+Rr.+Sylejman+Vokshi%2C+Prishtinë', 'active': True},
    {'name': 'Liburnia', 'city': 'Prishtinë', 'address': 'Rr. Bulevardi Nënë Tereza', 'maps_link': 'https://www.google.com/maps/search/?api=1&query=Liburnia%2C+Rr.+Bulevardi+Nënë+Tereza%2C+Prishtinë', 'active': True},
    {'name': 'Miqt', 'city': 'Prishtinë', 'address': 'Rr. UÇK', 'maps_link': 'https://www.google.com/maps/search/?api=1&query=Miqt%2C+Rr.+UÇK%2C+Prishtinë', 'active': True},
    {'name': 'Pishat', 'city': 'Prishtinë', 'address': 'Rr. Ilaz Agushi', 'maps_link': 'https://www.google.com/maps/search/?api=1&query=Pishat%2C+Rr.+Ilaz+Agushi%2C+Prishtinë', 'active': True},
    {'name': 'Renaissance', 'city': 'Prishtinë', 'address': 'Rr. Nazim Gafurri', 'maps_link': 'https://www.google.com/maps/search/?api=1&query=Renaissance%2C+Rr.+Nazim+Gafurri%2C+Prishtinë', 'active': True},
    {'name': 'Soma Book Station', 'city': 'Prishtinë', 'address': 'Rr. Rexhep Luci', 'maps_link': 'https://www.google.com/maps/search/?api=1&query=Soma+Book+Station%2C+Rr.+Rexhep+Luci%2C+Prishtinë', 'active': True},
    {'name': 'Symphony', 'city': 'Prishtinë', 'address': 'Rr. Perandori Justinian', 'maps_link': 'https://www.google.com/maps/search/?api=1&query=Symphony%2C+Rr.+Perandori+Justinian%2C+Prishtinë', 'active': True},
    {'name': 'Tiffany', 'city': 'Prishtinë', 'address': 'Rr. Agim Ramadani', 'maps_link': 'https://www.google.com/maps/search/?api=1&query=Tiffany%2C+Rr.+Agim+Ramadani%2C+Prishtinë', 'active': True},
    {'name': 'Besimi', 'city': 'Prizren', 'address': 'Sheshi Shatërvani', 'maps_link': 'https://www.google.com/maps/search/?api=1&query=Besimi%2C+Sheshi+Shatërvani%2C+Prizren', 'active': True},
    {'name': 'Marashi', 'city': 'Prizren', 'address': 'Lidhja e Prizrenit', 'maps_link': 'https://www.google.com/maps/search/?api=1&query=Marashi%2C+Lidhja+e+Prizrenit%2C+Prizren', 'active': True},
]
