# Generated by Django 5.2.7 on 2026-10-04 19:58

import datetime
import django.contrib.postgres.fields
import django.db.migrations.operations.special
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import ejb.models
import ejb.data_migrations
import ejb.schema_align
import uuid
from django.db import migrations, models

import ejb.schema_align


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('instance_id', models.UUIDField(blank=True, null=True)),
                ('aud', models.CharField(default='authenticated', max_length=255, null=True)),
                ('role', models.CharField(default='authenticated', max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('encrypted_password', models.CharField(max_length=255, null=True)),
                ('email_confirmed_at', models.DateTimeField(null=True)),
                ('confirmation_sent_at', models.DateTimeField(null=True)),
                ('recovery_sent_at', models.DateTimeField(null=True)),
                ('last_sign_in_at', models.DateTimeField(null=True)),
                ('raw_app_meta_data', models.JSONField(default=dict, null=True)),
                ('raw_user_meta_data', models.JSONField(default=dict, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('banned_until', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('phone', models.TextField(null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'auth"."users',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='ejb.authuser')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('age', models.IntegerField()),
                ('photo_path', models.TextField(null=True)),
                ('photo_face_ok', models.BooleanField(default=False)),
                ('is_tourist', models.BooleanField(default=False)),
                ('from_place', models.TextField(null=True)),
                ('langs', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=ejb.models.default_langs, size=None)),
                ('verified', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=5, max_digits=3)),
                ('tables_hosted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deactivated_at', models.DateTimeField(null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('user_preferences', models.JSONField(default=dict, null=True)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='Affinity',
            fields=[
                ('pk', models.CompositePrimaryKey('user_id', 'category', blank=True, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ejb.profile')),
                ('category', models.TextField()),
                ('score', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'affinity',
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('pk', models.CompositePrimaryKey('user_id', 'badge_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ejb.profile')),
                ('badge_id', models.TextField()),
                ('earned_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'badges',
            },
        ),
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ejb.profile')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'bans',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('pk', models.CompositePrimaryKey('blocker_id', 'blocked_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ejb.profile')),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ejb.profile')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'blocks',
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('pk', models.CompositePrimaryKey('a', 'b', blank=True, editable=False, primary_key=True, serialize=False)),
                ('b', models.ForeignKey(db_column='b', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ejb.profile')),
                ('a', models.ForeignKey(db_column='a', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ejb.profile')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'connections',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='ejb.profile')),
                ('icon', models.TextField(default='🔔')),
                ('body', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_tables', to='ejb.profile')),
                ('kind', models.TextField(default='tavoline')),
                ('category', models.TextField()),
                ('title', models.TextField()),
                ('area', models.TextField(null=True)),
                ('city', models.TextField()),
                ('to_city', models.TextField(null=True)),
                ('budget', models.TextField(null=True)),
                ('maps_link', models.TextField(null=True)),
                ('time_label', models.TextField()),
                ('starts_at', models.DateTimeField(null=True)),
                ('spots', models.IntegerField()),
                ('women_only', models.BooleanField(default=False)),
                ('mystery', models.BooleanField(default=False)),
                ('revealed', models.BooleanField(default=True)),
                ('langs', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=ejb.models.default_langs, size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('description', models.TextField(default='')),
                ('status', models.TextField(default='open')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_datetime', models.DateTimeField()),
                ('men_only', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tables',
            },
        ),
        migrations.CreateModel(
            name='WednesdayRestaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('city', models.TextField()),
                ('address', models.TextField()),
                ('maps_link', models.TextField(null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'wednesday_restaurants',
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('provider_id', models.TextField()),
                ('identity_data', models.JSONField(default=dict)),
                ('provider', models.TextField()),
                ('last_sign_in_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('email', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='ejb.authuser')),
            ],
            options={
                'db_table': 'auth"."identities',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ejb.profile')),
                ('amount_cents', models.IntegerField()),
                ('currency', models.TextField(default='EUR')),
                ('provider', models.TextField()),
                ('provider_ref', models.TextField()),
                ('status', models.TextField(default='paid')),
                ('ticket_code', models.TextField(null=True)),
                ('refundable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ejb.table')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ejb.profile')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ejb.table')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('pk', models.CompositePrimaryKey('table_id', 'user_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='ejb.profile')),
                ('role', models.TextField(default='member')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='ejb.table')),
            ],
            options={
                'db_table': 'memberships',
            },
        ),
        migrations.CreateModel(
            name='ConnectionPick',
            fields=[
                ('pk', models.CompositePrimaryKey('table_id', 'picker_id', 'picked_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('picker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ejb.profile')),
                ('picked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ejb.profile')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ejb.table')),
            ],
            options={
                'db_table': 'connection_picks',
            },
        ),
        migrations.CreateModel(
            name='WednesdayGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('city', models.TextField()),
                ('dinner_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ejb.wednesdayrestaurant')),
            ],
            options={
                'db_table': 'wednesday_groups',
            },
        ),
        migrations.CreateModel(
            name='TasteProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='taste', serialize=False, to='ejb.profile')),
                ('group_size', models.TextField(null=True)),
                ('depth', models.TextField(null=True)),
                ('time_pref', models.TextField(null=True)),
                ('energy', models.TextField(null=True)),
                ('interests', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('field', models.TextField(null=True)),
                ('biz_sport', models.TextField(null=True)),
                ('weekend', models.TextField(null=True)),
                ('role', models.TextField(null=True)),
                ('music', models.TextField(null=True)),
                ('freq', models.TextField(null=True)),
                ('organizer', models.TextField(null=True)),
                ('humor', models.TextField(null=True)),
                ('new_people', models.TextField(null=True)),
                ('done', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'taste_profiles',
            },
        ),
        migrations.CreateModel(
            name='WednesdayParticipant',
            fields=[
                ('pk', models.CompositePrimaryKey('group_id', 'user_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='ejb.wednesdaygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ejb.profile')),
            ],
            options={
                'db_table': 'wednesday_participants',
            },
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('pk', models.CompositePrimaryKey('table_id', 'user_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='ejb.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ejb.profile')),
            ],
            options={
                'db_table': 'waitlist',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.TextField(default='pending')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='ejb.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='ejb.profile')),
            ],
            options={
                'db_table': 'requests',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('details', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.TextField(default='pending')),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ejb.table')),
                ('reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ejb.profile')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ejb.profile')),
                ('reviewed_by', models.ForeignKey(db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ejb.profile')),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('stars', models.IntegerField()),
                ('meet_again', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ejb.table')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ejb.profile')),
            ],
            options={
                'db_table': 'ratings',
            },
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['created_at'], name='idx_profiles_created_at'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(('age__gte', 18), ('age__lte', 99)), name='profiles_age_check'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(('first_name__length__gte', 1), ('first_name__length__lte', 40)), name='profiles_first_name_check'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(('last_name__length__gte', 1), ('last_name__length__lte', 40)), name='profiles_last_name_check'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 0), ('rating__lte', 5)), name='profiles_rating_check'),
        ),
        migrations.AddConstraint(
            model_name='identity',
            constraint=models.UniqueConstraint(fields=('provider_id', 'provider'), name='identities_provider_id_provider_unique'),
        ),
        migrations.AddConstraint(
            model_name='tasteprofile',
            constraint=models.CheckConstraint(condition=models.Q(('depth__in', ['thella', 'argetim', 'te-dyja'])), name='taste_profiles_depth_check'),
        ),
        migrations.AddConstraint(
            model_name='tasteprofile',
            constraint=models.CheckConstraint(condition=models.Q(('energy__in', ['introvert', 'mes', 'ekstrovert'])), name='taste_profiles_energy_check'),
        ),
        migrations.AddConstraint(
            model_name='tasteprofile',
            constraint=models.CheckConstraint(condition=models.Q(('group_size__in', ['vogla', 'mesatare', 'medha'])), name='taste_profiles_group_size_check'),
        ),
        migrations.AddConstraint(
            model_name='tasteprofile',
            constraint=models.CheckConstraint(condition=models.Q(('time_pref__in', ['paradite', 'pasdite', 'mbremje'])), name='taste_profiles_time_pref_check'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(condition=models.Q(('status', 'open')), fields=['city', 'category'], name='idx_tables_city_cat'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['created_at'], name='idx_tables_created_at'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(condition=models.Q(('status', 'open')), fields=['event_datetime'], name='idx_tables_event_datetime'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['host'], name='idx_tables_host'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.CheckConstraint(condition=models.Q(('event_datetime__gt', django.db.models.expressions.CombinedExpression(models.F('created_at'), '-', models.Value(datetime.timedelta(seconds=300))))), name='event_datetime_future'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.CheckConstraint(condition=models.Q(('maps_link__isnull', True), ('maps_link__iregex', '^https?://(www\\.)?(google\\.[a-z.]+/maps|maps\\.google\\.[a-z.]+|maps\\.app\\.goo\\.gl|goo\\.gl/maps)'), _connector='OR'), name='tables_maps_link_check'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['open', 'full', 'done', 'cancelled'])), name='tables_status_check'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.CheckConstraint(condition=models.Q(('title__length__gte', 2), ('title__length__lte', 120)), name='tables_title_check'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(condition=models.Q(('status', 'pending')), fields=['table'], name='idx_requests_table'),
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.UniqueConstraint(fields=('table', 'user'), name='requests_table_id_user_id_key'),
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'approved', 'rejected', 'confirmed', 'expired'])), name='requests_status_check'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'reviewed_banned', 'reviewed_dismissed', 'deleted_immediately'])), name='reports_status_check'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('table', 'rater'), name='ratings_table_id_rater_id_key'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(condition=models.Q(('stars__gte', 1), ('stars__lte', 5)), name='ratings_stars_check'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('ticket_code',), name='payments_ticket_code_key'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('user', 'table'), name='payments_user_id_table_id_key'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gte', 0)), name='payments_amount_cents_check'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['paid', 'failed', 'void'])), name='payments_status_check'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read', '-created_at'], name='idx_notifications_user'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['table', 'created_at'], name='idx_messages_table'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('body__length__gte', 1), ('body__length__lte', 2000)), name='messages_body_check'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['joined_at'], name='idx_memberships_joined_at'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user'], name='idx_memberships_user'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['host', 'member'])), name='memberships_role_check'),
        ),
        migrations.AddConstraint(
            model_name='connectionpick',
            constraint=models.CheckConstraint(condition=models.Q(('picker', models.F('picked')), _negated=True), name='connection_picks_check'),
        ),
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.CheckConstraint(condition=models.Q(('a__lt', models.F('b'))), name='connections_check'),
        ),
        migrations.AddConstraint(
            model_name='block',
            constraint=models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked')), _negated=True), name='blocks_check'),
        ),
        migrations.AddIndex(
            model_name='ban',
            index=models.Index(fields=['created_at'], name='idx_bans_created_at'),
        ),
        migrations.AddConstraint(
            model_name='affinity',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', -40), ('score__lte', 40)), name='affinity_score_check'),
        ),
        migrations.RunPython(ejb.data_migrations.seed_wednesday_restaurants, migrations.RunPython.noop),
        migrations.RunPython(
            code=ejb.schema_align.align,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
    ]
