# Generated by Django 5.2.7 on 2026-10-04 19:59

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
import ejb.data_migrations
import ejb.models
import ejb.schema_align
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejb', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            code=ejb.data_migrations.drop_changed_constraints,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ejb.profile')),
                ('admin_name', models.TextField(null=True)),
                ('action', models.TextField()),
                ('target_type', models.TextField()),
                ('target_id', models.UUIDField(null=True)),
                ('target_label', models.TextField(null=True)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'admin_audit_log',
            },
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('token_hash', models.TextField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ejb.authuser')),
                ('kind', models.TextField()),
                ('redirect_to', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'backend"."auth_tokens',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.TextField()),
                ('payload', models.JSONField(default=dict)),
                ('status', models.TextField(default='pending')),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('run_after', models.DateTimeField(default=django.utils.timezone.now)),
                ('done_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'backend"."jobs',
            },
        ),
        migrations.CreateModel(
            name='LessonSubject',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('category', models.TextField()),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'lesson_subjects',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tutor', serialize=False, to='ejb.profile')),
                ('reviewed_by', models.ForeignKey(db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ejb.profile')),
                ('status', models.TextField(default='pending')),
                ('headline', models.TextField()),
                ('bio', models.TextField()),
                ('subjects', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=None, size=None)),
                ('teach_langs', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=ejb.models.default_teach_langs, size=None)),
                ('price_cents', models.IntegerField()),
                ('online', models.BooleanField(default=True)),
                ('in_person', models.BooleanField(default=False)),
                ('group_ok', models.BooleanField(default=False)),
                ('city', models.TextField()),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('years_experience', models.IntegerField(default=0)),
                ('education', models.TextField(null=True)),
                ('rejection_reason', models.TextField(null=True)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tutors',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='ejb.tutor')),
                ('subject', models.ForeignKey(db_column='subject', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ejb.lessonsubject')),
                ('kind', models.TextField()),
                ('title', models.TextField(null=True)),
                ('starts_at', models.DateTimeField()),
                ('duration_min', models.IntegerField()),
                ('format', models.TextField()),
                ('location_note', models.TextField(null=True)),
                ('max_students', models.IntegerField()),
                ('price_cents', models.IntegerField()),
                ('status', models.TextField(default='scheduled')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'lessons',
            },
        ),
        migrations.CreateModel(
            name='LessonParticipant',
            fields=[
                ('pk', models.CompositePrimaryKey('lesson_id', 'student_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ejb.profile')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='ejb.lesson')),
                ('status', models.TextField(default='requested')),
                ('note', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'lesson_participants',
            },
        ),
        migrations.CreateModel(
            name='NotificationBadgeLabel',
            fields=[
                ('label', models.TextField(primary_key=True, serialize=False)),
                ('badge_key', models.TextField()),
            ],
            options={
                'db_table': 'notification_badge_labels',
            },
        ),
        migrations.CreateModel(
            name='NotificationTextRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.TextField()),
                ('lang', models.TextField()),
                ('pattern', models.TextField()),
                ('param_names', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('priority', models.IntegerField(default=50)),
            ],
            options={
                'db_table': 'notification_text_rules',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('tier', models.TextField()),
                ('months', models.IntegerField(null=True)),
                ('price_cents', models.IntegerField(default=0)),
                ('monthly_table_limit', models.IntegerField(null=True)),
                ('monthly_join_limit', models.IntegerField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'plans',
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('token_hash', models.TextField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ejb.authuser')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'backend"."refresh_tokens',
            },
        ),
        migrations.CreateModel(
            name='StorageObject',
            fields=[
                ('pk', models.CompositePrimaryKey('bucket', 'path', blank=True, editable=False, primary_key=True, serialize=False)),
                ('bucket', models.TextField()),
                ('path', models.TextField()),
                ('owner', models.UUIDField(null=True)),
                ('size', models.BigIntegerField(default=0)),
                ('content_type', models.TextField(null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'backend"."storage_objects',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='ejb.profile')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ejb.plan')),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ejb.profile')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.TextField(default='active')),
                ('source', models.TextField()),
                ('amount_cents', models.IntegerField(default=0)),
                ('provider_ref', models.TextField(null=True)),
                ('note', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ejb.profile')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ejb.subscription')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ejb.plan')),
                ('handled_by', models.ForeignKey(db_column='handled_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ejb.profile')),
                ('code', models.TextField(default=ejb.models.new_order_code)),
                ('amount_cents', models.IntegerField()),
                ('status', models.TextField(default='pending')),
                ('handled_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'subscription_orders',
            },
        ),
        migrations.CreateModel(
            name='WednesdaySignup',
            fields=[
                ('pk', models.CompositePrimaryKey('user_id', 'dinner_date', blank=True, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ejb.profile')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ejb.wednesdaygroup')),
                ('dinner_date', models.DateTimeField()),
                ('city', models.TextField()),
                ('langs', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('status', models.TextField(default='signed_up')),
                ('premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'wednesday_signups',
            },
        ),
        migrations.CreateModel(
            name='LessonRoom',
            fields=[
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='room', serialize=False, to='ejb.lesson')),
                ('room_key', models.TextField(default=ejb.models.new_room_key)),
            ],
            options={
                'db_table': 'lesson_rooms',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='kind',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='params',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='table_title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='home_city',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='home_city_changed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarded_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='activity_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='table',
            name='share_code',
            field=models.TextField(null=True),
        ),
        migrations.RunPython(
            code=ejb.data_migrations.backfill_share_codes,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='table',
            name='share_code',
            field=models.TextField(default=ejb.models.new_share_code),
        ),
        migrations.AddField(
            model_name='table',
            name='skill_level',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='sport',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='wednesdaygroup',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ejb.table'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ejb.table'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ejb.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_preferences',
            field=models.JSONField(default=dict),
        ),
        migrations.AddIndex(
            model_name='ban',
            index=models.Index(fields=['user'], name='idx_bans_user'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['blocked'], name='idx_blocks_blocked'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['b'], name='idx_connections_b'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['kind'], name='idx_notifications_kind'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(condition=models.Q(('deactivated_at__isnull', False)), fields=['user'], name='idx_profiles_deactivated'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rater'], name='idx_ratings_rater'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reported'], name='idx_reports_reported'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['user'], name='idx_requests_user'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(condition=models.Q(('kind', 'sport'), ('status', 'open')), fields=['city', 'sport'], name='idx_tables_city_sport'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(condition=models.Q(('status', 'open')), fields=['city', 'event_datetime'], name='idx_tables_city_time'),
        ),
        migrations.AddIndex(
            model_name='waitlist',
            index=models.Index(fields=['user'], name='idx_waitlist_user'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(models.F('share_code'), name='tables_share_code_key'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['tavoline', 'vozitje', 'udhetim', 'darka_e_merkures', 'sport'])), name='tables_kind_check'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.CheckConstraint(condition=models.Q(('skill_level__isnull', True), ('skill_level__in', ['any', 'beginner', 'intermediate', 'advanced']), _connector='OR'), name='tables_skill_level_valid'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category', 'sport'), ('kind', 'sport'), ('sport__isnull', False)), models.Q(models.Q(('kind', 'sport'), _negated=True), ('skill_level__isnull', True), ('sport__isnull', True)), _connector='OR'), name='tables_sport_consistency'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.CheckConstraint(condition=models.Q(('sport__isnull', True), ('sport__in', ['football', 'basketball', 'volleyball', 'tennis', 'padel', 'table_tennis', 'badminton', 'running', 'fitness']), _connector='OR'), name='tables_sport_valid'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.CheckConstraint(condition=models.Q(('spots__gte', 1), models.Q(models.Q(('kind', 'sport'), ('spots__lte', 30)), models.Q(models.Q(('kind', 'sport'), _negated=True), ('spots__lte', 20)), _connector='OR')), name='tables_spots_check'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(condition=models.Q(('status', 'pending')), fields=['run_after'], name='idx_jobs_pending'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'running', 'done', 'failed'])), name='jobs_status_check'),
        ),
        migrations.AddField(
            model_name='payment',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ejb.lesson'),
        ),
        migrations.AddConstraint(
            model_name='notificationtextrule',
            constraint=models.UniqueConstraint(fields=('kind', 'lang', 'pattern'), name='notification_text_rules_kind_lang_pattern_key'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tier', 'basic'), ('months__isnull', True)), models.Q(models.Q(('tier', 'basic'), _negated=True), ('months__isnull', False)), _connector='OR'), name='plans_check'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_join_limit__isnull', True), models.Q(('monthly_join_limit__gte', 0), ('monthly_join_limit__lte', 1000)), _connector='OR'), name='plans_monthly_join_limit_check'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_table_limit__isnull', True), models.Q(('monthly_table_limit__gte', 0), ('monthly_table_limit__lte', 1000)), _connector='OR'), name='plans_monthly_table_limit_check'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('months__isnull', True), models.Q(('months__gte', 1), ('months__lte', 36)), _connector='OR'), name='plans_months_check'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('price_cents__gte', 0)), name='plans_price_cents_check'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('tier__in', ['basic', 'premium'])), name='plans_tier_check'),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ejb.subscription'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='idx_payments_created_at'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['table'], name='idx_payments_table'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('lesson__isnull', False)), fields=('user', 'lesson'), name='uq_payments_user_lesson'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['-created_at'], name='idx_admin_audit_created'),
        ),
        migrations.AddIndex(
            model_name='authtoken',
            index=models.Index(fields=['user', 'kind'], name='idx_auth_tokens_user'),
        ),
        migrations.AddConstraint(
            model_name='authtoken',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['signup', 'recovery'])), name='auth_tokens_kind_check'),
        ),
        migrations.AddIndex(
            model_name='lessonparticipant',
            index=models.Index(fields=['student'], name='idx_lesson_participants_student'),
        ),
        migrations.AddConstraint(
            model_name='lessonparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('note__isnull', True), ('note__length__lte', 500), _connector='OR'), name='lesson_participants_note_check'),
        ),
        migrations.AddConstraint(
            model_name='lessonparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['requested', 'accepted', 'confirmed', 'declined', 'cancelled'])), name='lesson_participants_status_check'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['user'], name='idx_refresh_tokens_user'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', '-ends_at'], name='idx_subscriptions_user'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='subscriptions_check'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['admin_grant', 'manual_payment', 'provider'])), name='subscriptions_source_check'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'revoked'])), name='subscriptions_status_check'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionorder',
            constraint=models.UniqueConstraint(fields=('code',), name='subscription_orders_code_key'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionorder',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user',), name='uq_one_pending_order'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionorder',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'paid', 'cancelled'])), name='subscription_orders_status_check'),
        ),
        migrations.AddIndex(
            model_name='tutor',
            index=models.Index(fields=['status'], name='idx_tutors_status'),
        ),
        migrations.AddIndex(
            model_name='tutor',
            index=django.contrib.postgres.indexes.GinIndex(fields=['subjects'], name='idx_tutors_subjects'),
        ),
        migrations.AddConstraint(
            model_name='tutor',
            constraint=models.CheckConstraint(condition=models.Q(('bio__length__gte', 30), ('bio__length__lte', 2000)), name='tutors_bio_check'),
        ),
        migrations.AddConstraint(
            model_name='tutor',
            constraint=models.CheckConstraint(condition=models.Q(('online', True), ('in_person', True), _connector='OR'), name='tutors_check'),
        ),
        migrations.AddConstraint(
            model_name='tutor',
            constraint=models.CheckConstraint(condition=models.Q(('education__isnull', True), ('education__length__lte', 200), _connector='OR'), name='tutors_education_check'),
        ),
        migrations.AddConstraint(
            model_name='tutor',
            constraint=models.CheckConstraint(condition=models.Q(('headline__length__gte', 5), ('headline__length__lte', 120)), name='tutors_headline_check'),
        ),
        migrations.AddConstraint(
            model_name='tutor',
            constraint=models.CheckConstraint(condition=models.Q(('lat__isnull', True), models.Q(('lat__gte', -90), ('lat__lte', 90)), _connector='OR'), name='tutors_lat_check'),
        ),
        migrations.AddConstraint(
            model_name='tutor',
            constraint=models.CheckConstraint(condition=models.Q(('lng__isnull', True), models.Q(('lng__gte', -180), ('lng__lte', 180)), _connector='OR'), name='tutors_lng_check'),
        ),
        migrations.AddConstraint(
            model_name='tutor',
            constraint=models.CheckConstraint(condition=models.Q(('price_cents__gte', 0), ('price_cents__lte', 20000)), name='tutors_price_cents_check'),
        ),
        migrations.AddConstraint(
            model_name='tutor',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'approved', 'rejected', 'suspended'])), name='tutors_status_check'),
        ),
        migrations.AddConstraint(
            model_name='tutor',
            constraint=models.CheckConstraint(condition=models.Q(('subjects__len__gte', 1), ('subjects__len__lte', 12)), name='tutors_subjects_check'),
        ),
        migrations.AddConstraint(
            model_name='tutor',
            constraint=models.CheckConstraint(condition=models.Q(('years_experience__gte', 0), ('years_experience__lte', 60)), name='tutors_years_experience_check'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(condition=models.Q(('kind', 'group'), ('status', 'scheduled')), fields=['subject', 'starts_at'], name='idx_lessons_group_upcoming'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['tutor', 'starts_at'], name='idx_lessons_tutor'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'group'), ('max_students', 1), _connector='OR'), name='lessons_check'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(condition=models.Q(('duration_min__in', [30, 45, 60, 90, 120])), name='lessons_duration_min_check'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(condition=models.Q(('format__in', ['online', 'in_person'])), name='lessons_format_check'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['individual', 'group'])), name='lessons_kind_check'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(condition=models.Q(('location_note__isnull', True), ('location_note__length__lte', 200), _connector='OR'), name='lessons_location_note_check'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(condition=models.Q(('max_students__gte', 1), ('max_students__lte', 30)), name='lessons_max_students_check'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(condition=models.Q(('price_cents__gte', 0), ('price_cents__lte', 100000)), name='lessons_price_cents_check'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['scheduled', 'cancelled'])), name='lessons_status_check'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(condition=models.Q(('title__isnull', True), models.Q(('title__length__gte', 3), ('title__length__lte', 120)), _connector='OR'), name='lessons_title_check'),
        ),
        migrations.AddIndex(
            model_name='wednesdaysignup',
            index=models.Index(condition=models.Q(('status', 'signed_up')), fields=['dinner_date', 'city'], name='idx_wed_signups_open'),
        ),
        migrations.AddConstraint(
            model_name='wednesdaysignup',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['signed_up', 'grouped', 'waitlisted', 'cancelled'])), name='wednesday_signups_status_check'),
        ),
        migrations.RunPython(
            code=ejb.data_migrations.seed_reference_data,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=ejb.data_migrations.backfill_payment_snapshots,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=ejb.data_migrations.classify_old_notifications,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=ejb.data_migrations.backfill_badges,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=ejb.data_migrations.backfill_onboarded_at,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=ejb.data_migrations.backfill_home_city,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=ejb.schema_align.align,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
    ]
