/**
 * Cloudflare Pages Function for shared table links: /t/<code>
 *
 * Link previews (WhatsApp, Facebook, Instagram, Telegram, X, iMessage) are
 * generated by crawlers that do not run JavaScript, so the per-table title,
 * time and free seats are written into the HTML here. People get the normal
 * app (index.html), which opens the table itself.
 *
 * Only the public preview is used (table_share_preview): never the maps link,
 * address or participants, and secret places stay secret.
 */

const KIND = {
  tavoline: 'Tavolinë', sport: 'Sport', vozitje: 'Vozitje', udhetim: 'Udhëtim', mesim: 'Mësim',
}

function fmtWhen(iso) {
  if (!iso) return ''
  try {
    return new Intl.DateTimeFormat('sq-AL', {
      timeZone: 'Europe/Belgrade', weekday: 'short', day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit', hour12: false,
    }).format(new Date(iso))
  } catch { return '' }
}

async function loadConfig(env, request) {
  if (env.SUPABASE_URL && env.SUPABASE_ANON_KEY) return { url: env.SUPABASE_URL, anonKey: env.SUPABASE_ANON_KEY }
  try {
    const r = await env.ASSETS.fetch(new URL('/share-config.json', request.url))
    if (r.ok) return await r.json()
  } catch { /* fall through */ }
  return null
}

export async function onRequestGet({ request, env, params }) {
  const indexRes = await env.ASSETS.fetch(new URL('/', request.url))
  const code = String(params.code || '').toLowerCase()
  if (!/^[a-z0-9-]{6,64}$/.test(code)) return indexRes

  let p = null
  try {
    const cfg = await loadConfig(env, request)
    if (cfg?.url && cfg?.anonKey) {
      const r = await fetch(`${cfg.url}/rest/v1/rpc/table_share_preview`, {
        method: 'POST',
        headers: { apikey: cfg.anonKey, Authorization: `Bearer ${cfg.anonKey}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({ p_code: code }),
        cf: { cacheTtl: 60, cacheEverything: true },
      })
      if (r.ok) p = await r.json()
    }
  } catch { /* preview is best-effort; the app still works */ }

  const origin = new URL(request.url).origin
  const url = `${origin}/t/${code}`
  let title = 'ejaBashkohu'
  let desc = 'Eja bashkohu në tavolinë. Platforma sociale e Kosovës.'
  if (p) {
    const name = p.secret ? 'Vend sekret' : p.title
    const place = p.to_city ? `${p.city} → ${p.to_city}` : [p.area, p.city].filter(Boolean).join(', ')
    const free = Math.max(0, (p.spots || 0) - (p.taken || 0))
    const seats = p.status === 'open' ? `${free} nga ${p.spots} vende të lira`
      : p.status === 'full' ? 'Plot' : p.status === 'past' ? 'Ka kaluar' : 'E mbyllur'
    title = `${name} · ${KIND[p.kind] || 'Tavolinë'} · ejaBashkohu`
    desc = [fmtWhen(p.event_datetime) || p.time_label, place, seats, p.host_first_name ? `Nikoqir: ${p.host_first_name}` : '']
      .filter(Boolean).join(' · ')
  }

  const setContent = (v) => ({ element(el) { el.setAttribute('content', v) } })
  const res = new HTMLRewriter()
    .on('title', { element(el) { el.setInnerContent(title) } })
    .on('meta[name="description"]', setContent(desc))
    .on('meta[property="og:title"]', setContent(title))
    .on('meta[property="og:description"]', setContent(desc))
    .on('meta[property="og:url"]', setContent(url))
    .on('meta[name="twitter:title"]', setContent(title))
    .on('meta[name="twitter:description"]', setContent(desc))
    .on('meta[name="twitter:url"]', setContent(url))
    .on('link[rel="canonical"]', { element(el) { el.setAttribute('href', url) } })
    .transform(indexRes)

  const headers = new Headers(res.headers)
  headers.set('Cache-Control', 'public, max-age=60')
  // Shared tables are personal invitations, not search-engine pages.
  headers.set('X-Robots-Tag', 'noindex')
  return new Response(res.body, { status: 200, headers })
}
